for _ in range(1):
    for _ in range(1):
      print(" INSTALL VIRS ") 
  

for _ in range(1):
    for _ in range(1):
      print(" LODING....VIRS") 
  
for _ in range(1):
    for _ in range(1):
      print(" INSTALL VIRSTOOLS ") 
  


for _ in range(1):
    for _ in range(1):
      print(" VIRSTOOLS SUCCESSFULLY INSTALLED ") 
  

for _ in range(1):
    for _ in range(1):
      print(" VIRS SUCCESSFULLY INSTALLED ") 
  
